config/routes.rb
Rails.application.routes.draw do
  get "search_products/index"
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "filter_items", to: "products#filter_products", as: "filter_items"
  resources :users
  resources :products
  resources :categories
  namespace :admin do
    resources :products
    resources :search_products
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  scope :recent, ->{order name: :asc}
  has_many :childs, class_name: Category.name, foreign_key: :child_of, dependent: :destroy
  has_one :parent, class_name: Category.name, primary_key: :child_of, foreign_key: :id
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.select(:id, :name).recent
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% if category.parent.blank? && category.childs.blank? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <%= link_to category.name, filter_items_path(cate_id: category.id), remote: true %>
      </h4>
    </div>
  </div>
<% elsif category.childs.present? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordian" href="#cate-<%= category.id %>">
          <span class="badge pull-right"><i class="fa fa-plus"></i></span>
          <%= category.name %>
        </a>
      </h4>
    </div>
    <div id="cate-<%= category.id %>" class="panel-collapse collapse">
      <div class="panel-body">
        <ul>
          <%= render partial: "categories/sub_categories", collection: category.childs, as: :sub_categories %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/_sub_categories.html.erb
<% if sub_categories.childs.blank? %>
<li><%= link_to sub_categories.name, filter_items_path(cate_id: sub_categories.id), remote: true %></li>
<% else %>
  <ul>
    <% render partial: "sub_categories",collection: sub_categories.child_cates, as: :sub_categories %>
  </ul>
<% end %>

app/views/categories/index.html.erb
<% if @categories.any? %>
  <%= render @categories %>
<% end %>

app/views/categories/show.js.erb
$('#product-js').html('<%= j render('shared/products') %>')