config/routes.rb
Rails.application.routes.draw do
  get "search_products/index"
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "filter_items", to: "products#filter_products", as: "filter_items"
  resources :users
  resources :products
  resources :categories
  namespace :admin do
    resources :products
    resources :search_products
  end
end

app/views/layouts/404.html.erb
<div class="container text-center">
  <div class="logo-404">
    <%= link_to image_tag(image_path("home/logo.png")), root_path %>
  </div>
  <div class="content-404">
    <%= image_tag(image_path("404/404.png"), class: "img-responsive") %>
    <h1><b><%= t(".opp") %></b> <%= t(".couldfind") %></h1>
    <p><%= t(".message") %></p>
    <%= link_to t(".bring"), root_path %>
  </div>
</div>

app/views/layouts/_filter_alphabet.html.erb
<%= link_to t(".filter"), :controller => "products", :action => "filter_products", remote: true, :alphabet => 1, id: "button-alphabet" %>

app/views/layouts/_filter_products.html.erb
<%= form_tag url_for(controller: "products",
  action: "filter_products"), method: :get, remote: true do %>
  <%= number_field :cost_min, params[:cost_min], placeholder: t(".min") %>
  <%= number_field :cost_max, params[:cost_max], placeholder: t(".max") %>
  <br>
  <button type="submit" class="submit-search"><i class="fa fa-search"></i></button>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="companyinfo">
            <h2><span>e</span>-shopper</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag(image_path("home/iframe1.png")) %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag(image_path("home/iframe2.png")) %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag(image_path("home/iframe3.png")) %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>

          <div class="col-sm-3">
            <div class="video-gallery text-center">
              <a href="#">
                <div class="iframe-img">
                  <%= image_tag(image_path("home/iframe4.png")) %>
                </div>
                <div class="overlay-icon">
                  <i class="fa fa-play-circle-o"></i>
                </div>
              </a>
              <p>Circle of Hands</p>
              <h2>24 DEC 2014</h2>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="address">
            <%= image_tag(image_path("home/map.png")) %>
            <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-widget">
    <div class="container">
      <div class="row">
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Service</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Online Help</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Order Status</a></li>
              <li><a href="#">Change Location</a></li>
              <li><a href="#">FAQ’s</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Quock Shop</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">T-Shirt</a></li>
              <li><a href="#">Mens</a></li>
              <li><a href="#">Womens</a></li>
              <li><a href="#">Gift Cards</a></li>
              <li><a href="#">Shoes</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>Policies</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Terms of Use</a></li>
              <li><a href="#">Privecy Policy</a></li>
              <li><a href="#">Refund Policy</a></li>
              <li><a href="#">Billing System</a></li>
              <li><a href="#">Ticket System</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <ul class="nav nav-pills nav-stacked">
              <li><a href="#">Company Information</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#">Store Location</a></li>
              <li><a href="#">Affillate Program</a></li>
              <li><a href="#">Copyright</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <div class="single-widget">
            <h2>About Shopper</h2>
            <form action="#" class="searchform">
              <input type="text" placeholder="Your email address" />
              <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
              <p>Get the most recent updates from <br />our site and be updated your self...</p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
        <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="header-middle">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <%= link_to image_tag(image_path("home/logo.png")), root_path %>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              <li><%= link_to t(".signup"), new_user_path %></li>
              <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
              <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
              <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
              <% if logged_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= t ".account" %><i class="fa fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t(".profile"), current_user %></li>
                    <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
                    <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li>
                  <%= link_to login_path do %>
                    <i class="fa fa-lock"></i>
                    <%= t ".login" %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="header-bottom">
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><%= link_to t(".home"), root_path %></li>
              <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                <ul role="menu" class="sub-menu">
                  <li><a href="shop.html">Products</a></li>
                  <li><a href="product-details.html">Product Details</a></li>
                  <li><a href="checkout.html">Checkout</a></li>
                  <li><a href="cart.html">Cart</a></li>
                  <li><a href="login.html">Login</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                <ul role="menu" class="sub-menu">
                  <li><a href="blog.html">Blog List</a></li>
                  <li><a href="blog-single.html">Blog Single</a></li>
                </ul>
              </li>
              <li><%= link_to t(".contact"), contact_path %></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <%= render "layouts/search" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag url_for(controller: "search_products",
  action: "index"), method: :get, remote: true do %>
  <%= text_field_tag :query, params[:query],
  placeholder: t(".search") %>
  <button type="submit" class="submit-search"><i class="fa fa-search"></i></button>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_slider.html.erb
<div id="slider-carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#slider-carousel" data-slide-to="1"></li>
    <li data-target="#slider-carousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <div class="col-sm-6">
        <h1>E-SHOPPER</h1>
        <h2>Free E-Commerce Template</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
        <button type="button" class="btn btn-default get">Get it now</button>
      </div>
      <div class="col-sm-6">
        <%= image_tag(image_path("home/girl1.jpg"), class: "girl img-responsive") %>
        <%= image_tag(image_path("home/pricing.png"), class: "pricing") %>
      </div>
    </div>
    <div class="item">
      <div class="col-sm-6">
        <h1><span>E</span>-SHOPPER</h1>
        <h2>100% Responsive Design</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
        <button type="button" class="btn btn-default get">Get it now</button>
      </div>
      <div class="col-sm-6">
        <%= image_tag(image_path("home/girl2.jpg"), class: "girl img-responsive") %>
        <%= image_tag(image_path("home/pricing.png"), class: "pricing") %>
      </div>
    </div>
    <div class="item">
      <div class="col-sm-6">
        <h1><span>E</span>-SHOPPER</h1>
        <h2>Free Ecommerce Template</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
        <button type="button" class="btn btn-default get">Get it now</button>
      </div>
      <div class="col-sm-6">
        <%= image_tag(image_path("home/girl3.jpg"), class: "girl img-responsive") %>
        <%= image_tag(image_path("home/pricing.png"), class: "pricing") %>
      </div>
    </div>
  </div>
  <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
    <i class="fa fa-angle-left"></i>
  </a>
  <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
    <i class="fa fa-angle-right"></i>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>